tenant:
  namespaces:
    names:
      - name: "project-webapp-id1"
        networkPolicy:
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      tenant: "project-webapp-id1"
          egress:
            - to:
                - podSelector: {}  # Allow all traffic
        resourceQuota:
          hard:
            requests.cpu: "4"
            requests.memory: "8Gi"
            limits.cpu: "8"
            limits.memory: "16Gi"
            pods: "10"
        limitRange:
          limits:
            - default:
                cpu: "500m"
                memory: "512Mi"
              defaultRequest:
                cpu: "100m"
                memory: "10Mi"
              type: "Container"

      - name: "project-apiapp-id2"
        networkPolicy:
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      tenant: "project-apiapp-id2"
          egress:
            - to:
                - podSelector: {}  # Allow all traffic
        resourceQuota:
          hard:
            requests.cpu: "2"
            requests.memory: "4Gi"
            limits.cpu: "4"
            limits.memory: "8Gi"
            pods: "5"
        limitRange:
          limits:
            - default:
                cpu: "250m"
                memory: "256Mi"
              defaultRequest:
                cpu: "100m"
                memory: "50Mi"
              type: "Container"
