{{- range .Values.tenant.namespaces.names }}
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: {{ .name }}
spec:
  limits:
    {{- toYaml .limitRange.limits | nindent 4 }}
---
{{- end }}
