{{- range .Values.tenant.namespaces }}
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .name }}
spec:
  limits:
    - default:
        cpu: "{{ .limitRange.default.cpu }}"
        memory: "{{ .limitRange.default.memory }}"
      defaultRequest:
        cpu: "{{ .limitRange.defaultRequest.cpu }}"
        memory: "{{ .limitRange.defaultRequest.memory }}"
      type: Container
---
{{- end }}
