apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tenant-traffic
  namespace: {{ .Values.tenant.namespaces.names | first }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              tenant: {{ .Values.tenant.namespaces.names | first }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              tenant: {{ .Values.tenant.namespaces.names | first }}
---
{{- range .Values.tenant.namespaces.names | rest }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tenant-traffic
  namespace: {{ . }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              tenant: {{ . }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              tenant: {{ . }}
---
{{- end }}
