{{- range .Values.tenant.namespaces.names }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tenant-traffic
  namespace: {{ .name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .networkPolicy.egress | nindent 4 }}
---
{{- end }}
