{{- range .Values.tenant.namespaces }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-custom-traffic
  namespace: {{ .name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .networkPolicy.allowFromNamespaces }}
        - namespaceSelector:
            matchLabels:
              tenant: "{{ . }}"
        {{- end }}
  egress:
    - to:
        - namespaceSelector: {}
---
{{- end }}
