{{- range .Values.tenant.namespaces }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: {{ .name }}
spec:
  hard:
    requests.cpu: "{{ .resourceQuota.requests.cpu }}"
    requests.memory: "{{ .resourceQuota.requests.memory }}"
    limits.cpu: "{{ .resourceQuota.limits.cpu }}"
    limits.memory: "{{ .resourceQuota.limits.memory }}"
    pods: "{{ .resourceQuota.pods }}"
---
{{- end }}
