{{- range .Values.tenant.namespaces.names }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{ .name }}
spec:
  hard:
    {{- toYaml .resourceQuota.hard | nindent 4 }}
---
{{- end }}
